Support opening conversation activity by tapping notification
skygear-demo/android-chat-uikit-demo pull request #20
Opened 2018-03-15 11:41 UTC by howawong

- Add PushListenerService

Connects #15

2018-03-19 10:15 UTC, carmenlau requested changes

2018-03-19 10:15 UTC, carmenlau commented on app/src/main/java/io/skygear/chatdemo/PushListenerService.java
> +        mChatContainer.getConversation(conversationId, new GetCallback<Conversation>() {
I think it is not a good option to fetch conversation when user received message, if another user keep sending messages to a room that have many people room. All the users got the message will fetch the conversation at the same time and cause server performance issue.

2018-03-19 10:15 UTC, carmenlau commented on app/src/main/java/io/skygear/chatdemo/PushListenerService.java
> +        mainActivityIntent.addFlags(Intent.FLAG_ACTIVITY_BROUGHT_TO_FRONT);
Would like to know what is `mainActivityIntent` for?

2018-03-21 02:22 UTC, howawong commented on app/src/main/java/io/skygear/chatdemo/PushListenerService.java
> +        mainActivityIntent.addFlags(Intent.FLAG_ACTIVITY_BROUGHT_TO_FRONT);
Oh my bad, will delete that.

2018-03-21 02:23 UTC, howawong commented on app/src/main/java/io/skygear/chatdemo/PushListenerService.java
> +        mChatContainer.getConversation(conversationId, new GetCallback<Conversation>() {
You are right. However, shall I implement this in this demo project or chat SDK project?

2018-04-04 08:08 UTC, carmenlau commented
I will close this PR, please open another after update. Thanks! :)

2018-04-04 08:08 UTC, closed without merging